openapi: 3.0.0

info:
  version: "1.0"
  title: "LBAW Invents Web API"
  description: "Web Resources Specification (A7) for Invents"

servers:
  url: http://lbaw2354.lbaw.fe.up.pt/
  description: Production server

# ver isto
externalDocs:
  description: Find more info here.
  url: https://web.fe.up.pt/~ssn/wiki/teach/lbaw/invents/a07

tags:
  - name: "M01: Authentication and Individual Profile"
  - name: "M02: Events"
  - name: "M03: Comments and polls"
  - name: "M04: Invite and join events"
  - name: "M05: User Administration and Static pages"

paths:
  /login:
    get:
      operationId: R101
      summary: "R101: Login Form"
      description: "Provide login form. Access: PUB"
      tags:
        - "M01: Authentication and Individual Profile"
      responses:
        "200":
          description: "Ok. Show Log-in UI"
    post:
      operationId: R102
      summary: "R102: Login Action"
      description: "Processes the login form submission. Access: PUB"
      tags:
        - "M01: Authentication and Individual Profile"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password

      responses:
        "302":
          description: "Redirect after processing the login credentials."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful authentication. Redirect to home."
                  value: "/"
                302Error:
                  description: "Failed authentication. Redirect to login form."
                  value: "/login"

  /logout:
    post:
      operationId: R103
      summary: "R103: Logout Action"
      description: "Logout the current authenticated user. Access: USR, ADM"
      tags:
        - "M01: Authentication and Individual Profile"
      responses:
        "302":
          description: "Redirect after processing logout."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful logout. Redirect to login form."
                  value: "/login"

  /register:
    get:
      operationId: R104
      summary: "R104: Register Form"
      description: "Provide new user registration form. Access: PUB"
      tags:
        - "M01: Authentication and Individual Profile"
      responses:
        "200":
          description: "Ok. Show Sign-Up UI"

    post:
      operationId: R105
      summary: "R105: Register Action"
      description: "Processes the new user registration form submission. Access: PUB"
      tags:
        - "M01: Authentication and Individual Profile"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                confirmPassword:
                  type: string
                  format: password
              required:
                - name
                - username
                - email
                - password

      responses:
        "302":
          description: "Redirect after processing the new user information."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful authentication. Redirect to home."
                  value: "/"
                302Failure:
                  description: "Failed authentication. Redirect to login form."
                  value: "/login"

  /users/{id}:
    get:
      operationId: R106
      summary: "R106: View user profile"
      description: "Show the individual user profile. Access: USR."
      tags:
        - "M01: Authentication and Individual Profile"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: "Ok. Show User Profile UI"

  /users/{id}/edit:
    get:
      operationId: R107
      summary: "R107: Edit user profile page"
      description: "Show the edit user form. Access: USR"
      tags:
        - "M01: Authentication and Individual Profile"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: "Ok. Show Edit User UI"
        "403":
          description: "Forbidden. Login required."
          value: "/login"
    put:
      operationId: R108
      summary: "R108: Update User"
      description: "Processes the update user form submission. Access: USR." //TODO USR ou OWN?
      tags:
        - "M01: Authentication and Individual Profile"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                name:
                  type: string
                description:
                  type: string
                password:
                  type: string
                blocked:
                  type: boolean
                admin:
                  type: boolean
      responses:
        "200":
          description: "Update successful. Redirect to user page."
        "400":
          description: "Bad request"
  api/users/{id}/owned-events:
    get:
      operationId: R109
      summary: "R109: Search Owned Events API"
      description: "Search for events owned by the user and returns the results as JSON. Access: USR"
      tags:
        - "M01: Authentication and Individual Profile"
      parameters:
        //TODO Não estudei direito essa parte ainda
      responses:
        "200"
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    obs:
                      type: string
                    year:
                      type: string
                    owner:
                      type: string
                    type:
                      type: string


    api/users/{id}/joined-events:
    get:
      operationId: R110
      summary: "R110: Search for Joined Events API"
      description: "Search for events joined by the user and returns the results as JSON. Access: USR"
      tags:
        - "M01: Authentication and Individual Profile"
      parameters:
        TODO Não estudei direito essa parte ainda
      responses:
        "200"
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    obs:
                      type: string
                    year:
                      type: string
                    owner:
                      type: string
                    type:
                      type: string

  /home:
    get:
      operationId: R201
      summary: "R201: Home Page"
      description: "Show the home page. Access: PUB"
      tags:
        - "M02: Events"
      responses:
        "200":
          description: "Ok. Show Home UI"

  /events:
    get:
      operationId: R202
      summary: "R202: Events page"
      description: "Shows the events page UI. Access: PUB."
      tags:
        - "M02: Events"
      responses:
        "200":
          description: "Ok. Show Events UI"

  /events/createEvent:
    get:
      operationId: R203
      summary: "R203: Create Event Page"
      description: "Show the create event form. Access: USR."
      tags:
        - "M02: Events"
      responses:
        "200":
          description: "Ok. Show Create Event UI"
        "403":
          description: "Forbidden. Login required."

    post:
      operationId: R204
      summary: "R204: Create Event Action"
      description: "Processes the create event form submission. Access: USR."
      tags:
        - "M02: Events"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                eventTitle:
                  type: string
                eventDescription:
                  type: string
                eventDate:
                  type: string
                  format: date
                eventLocation:
                  type: string
                eventTags:
                  type: json
                price:
                  type: string
                  format: number
                eventCapacity:
                  type: string
                  format: number
                openToJoin:
                  type: boolean
                public:
                  type: boolean

      responses:
        "302":
          description: "Redirect after processing the new event information."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful creation of the event. Redirect to event page."
                  value: "/events/{id}"
                302Failure:
                  description: "Failed creation of the event. Redirect to create event page."
                  value: "/events/createEvent"

  /events/{id}:
    get:
      operationId: R205
      summary: "R205: View Event"
      description: "Show individual event. Access: PUB USR OWN."
      tags:
        - "M02: Events"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: "Ok. Show Event UI"
        "403":
          description: "Forbidden. Private event. Login required."
          value: "/events"

    delete:
      operationId: R206
      summary: "R206: Delete Event"
      description: "Delete event. Access: OWN."
      tags:
        - "M02: Events"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "202":
          description: "Accepted. Event deleted."
          value: "/events"
        "401":
          description: "Unauthorized. User not owner of event."
          value: "/events/{id}"

  /events/{id}/join:
    post:
      operationId: R207
      summary: "R207: Join Event"
      description: "Join event. Access: USR."
      tags:
        - "M02: Events"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "202":
          description: "Accepted. Event joined."
          value: "/events/{id}"
        "400":
          description: "Bad Request. "
          value: "/events/{id}"

  /events/{id}/askToJoin:
    post:
      operationId: R208
      summary: "R208: Ask to Join Event"
      description: "Ask to join event. Access: USR."
      tags:
        - "M02: Events"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: "OK. Request sent."
          value: "/events/{id}"
        "400":
          description: "Bad Request. Not sent."
          value: "/events/{id}"

  /events/{id}/leave:
    post:
      operationId: R209
      summary: "R209: Leave Event"
      description: "Leave event. Access: USR."
      tags:
        - "M02: Events"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "202":
          description: "Accepted. Event left."
          value: "/events/{id}"
        "400":
          description: "Bad Request. Did not left event."
          value: "/events/{id}"

  /events/{id}/edit:
    get:
      operationId: R210
      summary: "R210: Edit Event"
      description: "Show the edit event form. Access: USR OWN."
      tags:
        - "M02: Events"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: "Ok. Show Edit Event UI"
        "403":
          description: "Forbidden. Private event. Login required."
          value: "/events"

    put:
      operationId: R211
      summary: "R211: Update Event"
      description: "Processes the update event form submission. Access: OWN."
      tags:
        - "M02: Events"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                eventDescription:
                  type: string
                eventDate:
                  type: string
                  format: date
                eventLocation:
                  type: string
                eventTags:
                  type: json
                price:
                  type: string
                  format: number
                eventCapacity:
                  type: string
                  format: number
                openToJoin:
                  type: boolean
                public:
                  type: boolean

      responses:
        "200":
          description: "Update successful. Redirect to event page."
        "400":
          description: "Bad request"

  events/{id}/participants:
    get:
      operationId: R212
      summary: "R212: View event participants"
      description: "Show all users that joined the event. Access: OWN."
      tags:
        - "M02: Events"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: "Ok. Show Event Participants UI"
        "403":
          description: "Forbidden. Login as owner required."
          value: "/events"
    post: //TODO POST ou DELETE?
      operationId: R213
      summary: "R213: Remove User from Event"
      description: "Remove user from event. Access: OWN."
      tags:
        - "M02: Events"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "202":
          description: "Accepted. User removed from event deleted."
          value: "/events/{id}/participants"
        "401":
          description: "Unauthorized. User not owner of event."
          value: "/events/{id}"



  /api/events:
    get:
      operationId: R214
      summary: "R214: Search Events API"
      description: "Searches for events and returns the results as JSON. Access: PUB."
      tags:
        - "M02: Events"
      parameters:
        - in: query
          name: query
          description: String to use for full-text search
          schema:
            type: string
          required: false
        - in: query
          name: names
          description: Names of the events
          schema:
            type: string
        - in: query
          name: tags
          description: Tags of the events
          schema:
            type: string
          required: false
        - in: query
          name: date
          description: Dates for the events
          schema:
            type: boolean
          required: false
        - in: query
          name: owner
          description: Boolean with the owner flag value
          schema:
            type: boolean
          required: false
        - in: query
          name: classification
          description: Integer corresponding to the work classification
          schema:
            type: integer
          required: false
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    obs:
                      type: string
                    year:
                      type: string
                    owner:
                      type: string
                    type:
                      type: string
        
  /events/{id}/invite-user:
    post:
      operationId: R401
      summary: "R401: Invite User to Public Event"
      description: "Invite a user to a public event. Access: USR"
      tags:
        - "M04: Invite and join events"
      requestBody:
        required: true
        content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
               email:
                 type: string
             required:
                  - email